### ISSUE TITLE
Drop all files to add all data??

### ISSUE THREAD

**Issue by anguila** [ClimberAB/ClimberCustomReport#1]
If you drag a column of the 'Custom report' under its own container, it shows the 'Drop the files to add all data' panel on the bottom side of the page.

This is on sense 3.0

Cheers,

David

**Comment by kfsjostrand** [comment]
I have suppressed it as much as I can without being intrusive. The 'Drop the files to add all data' panel shows up sometimes if you drag it to quick and the event handler don't register fast enough.
