### ISSUE TITLE
Enhancement: Pivot tables as visualization option

### ISSUE THREAD

**Issue by schmidfaced** [ClimberAB/ClimberCustomReport#11]
This is a great extension object and fills a major gap for Qlik Sense where going into edit mode is simply overkill for many basic users who just need to export some quick data.  Being able to use a pivot table here would solve even more issues since the user would be able to easily move the dimensions/measures into a horizontal view which is what many are used to in excel.  We have a client who requires this functionality so if you're interested please reach out to me to discuss an opportunity to make this enhancement.  Thanks for all your work on this so far!

**Comment by ClimberExtensions** [comment]
Hi and thank you for your input and kind words!
We agree that adding pivot-tables would be a very nice addition. However, we will focus on our current customers and their request first so we are not taking third party requests at this time. If that changes or pivot tables are added we will of course let everyone know :-)
