### ISSUE TITLE
question regarding pivot-table

### ISSUE THREAD

**Issue by kuhbrille** [ClimberAB/ClimberCustomReport#12]
Hi,
thx for this great solution!
Works fine for us.

Now we would like to use it for a pivot table and want to add a dimension into the columns.
This works, but without adding to columns instead of rows.
app.visualization.create('pivot-table', [
                  "brand", "=sum(demand)"
          ]

I found this page, and can see, how to define the hypercube, but do not know how to transfer this into the .create statement.
Is there any example I can look at?
http://help.qlik.com/en-US/sense-developer/2.1/Subsystems/EngineAPI/Content/DiscoveringAndAnalysing/MakeSelections/select-values-in-pivot-table.htm

**Comment by ClimberExtensions** [comment]
Hi,
thanks for the positive feedback!

We are considering adding pivot-tables to the extension but no time schedule is set for that yet. 

Kind regards
/Michael
