### ISSUE TITLE
Right-click contextual menu is absent in web mashup (Hide fields/sortbar results in a dead-end)

### ISSUE THREAD

**Issue by cheenusj** [ClimberAB/ClimberCustomReport#13]
Hi Karl,

Firstly, thank you very much for this superb extension. It is extremely useful and makes the "user journey" that much easier to create their own tables.

I have noticed something that is a bit of a conundrum. When you make the extension available through a web mashup, the right-click contextual menu does not appear and can't be used. Is there a workaround for this.

The reason why I ask (and also for the conundrum), is that when a user clicks on the "hide fields/sortbar" in the web mashup, it disappears completely and the user reactivate it (right-click reaps nothing). The strangest part is that BOTH the original app (QVF) and the (server) published app to which the web mashup is pointing to, have their Custom Reports with "hidden" fields/sortbar, Right-clicking on either of apps (even on the one in my personal profile "Work" menu in hub) and restoring the "sortbar" then refreshes the web mashup too.

Any ideas on this? Is the QSR getting confused with the ObjectId. I would have thought that the combination of app UID and ObjectId are what would direct the web mashup as to where to look.

Also, is there any way of making the right-click menu available for users in the web mashup. Not being able to export the data they see in the Custom Report object hampers it use in web mashups to a great extent.

Many thanks. Kind regards.

Cheenu

**Comment by dionverbeke** [comment]
I have the same issue. Any help from Qlik?

**Comment by cheenusj** [comment]
Hi Dion,

I doubt Qlik supports extension that they themselves haven't developed.

I spoke with a Climber consultant/expert. Apparently the lack of the "export to Excel" is a known bug and has been resolved in the latest extension/zip, if this is the issue you're faced with. Delete the extension in QMC and re-import it. If you get an error message, ignore it. It should resolve the issue and you will be able to get the "export to Excel" button.

In regards to the the "hide" function, the only way to "reset" is by clearing the browser cache. I need to have a look and see if the behaviour of the browser could be modified to overcome this. If you have any thoughts or ideas on this, it would be extremely helpful.

I still haven't received any feedback per se on this issue, but will ask my contact in Climber if he knows about a workaround for it.

Kr,

Cheenu

**Comment by dionverbeke** [comment]
Hi, 

The issue occurs in a mashup where the bubbles to select the different options are not working (You can't right click in there).

I've worked around it temporarily by always showing the sortbar and modifying the icon in the angular template. 

If you are interested I can share the code.

My next task is : 

1. to introduce the pivot table in the extension.
2. remember selections by including them in a bookmark.

Kr,

Dion

**Comment by ClimberExtensions** [comment]
Thanks for posting issues to Github.
When creating mashups you need to create your own context menu. It's not an extension issue and it's the same for the built in visualizations. I think you should be able to use JQuery and grab the scope of the extension and then call the export function. 
I will in the next release add a feature to be able to hide the 'Hide sortbar' button, and be able to add an export to Excel button.
@dionverbeke  regarding the Excel export bug was not mashup releated. It was bug in the Visualization API, fixed in 3.1 SR3 i think, that didn't work with a virtual proxy. Look at the readme for details and workaround.

**Comment by ClimberExtensions** [comment]
Added ability to hide icons in the latest release.
