### ISSUE TITLE
Hi, we have upgraded to version 3.2 SR2 and did the even an upgrade on this really useful Ext.

### ISSUE THREAD

**Issue by SandegrenJohan** [ClimberAB/ClimberCustomReport#15]
First many thanks it's so useful!
When I use the extension it will show no table show you on a printscreen but when I export I get the right Dimensions and Measures. When I installed I deleted the former Version and imported the new one in QMC. Do you have any solution on this or have I done something? This extension is the best way when you control the data and then you can leave it to the users.
![image](https://cloud.githubusercontent.com/assets/22326152/24516860/6ca4a3da-157c-11e7-9613-70a490647150.png)

Best
Johan Sandegren

**Comment by kfsjostrand** [comment]
This looks like there is something wrong with Bootstrap. Make sure you download the latest version of the Custom Report and install it with the latest zip file in the build folder. 
If that doesn't work, the old version might be cached. Try and remove your browsing history and cache.

**Comment by kfsjostrand** [comment]
Version 1.0.12 is tested with 3.2 SR2 and should work. What browser are you using? Any error messages in the console?

**Comment by SandegrenJohan** [comment]
Thanks for the support tips.
I downloaded the latest version that now is 3 days old.
Deleted the my former version.
Imported the new version in QMC.
Using Chrome as browser and even tried Firefox without cache, same things happens that I show in the Printscreen.
Can't see any error messages in console, checked with other users to same thing.

**Comment by ClimberExtensions** [comment]
Try and recreate the visualization in an app and see if the new vis works.

**Comment by SandegrenJohan** [comment]
Have tried that to but I found something else when i look at About for the extension this could not be right
![image](https://cloud.githubusercontent.com/assets/22326152/24546671/a5deedfa-160c-11e7-9516-f1247e3cdccf.png)

We shall restart our Nodes and see if there are some sync issues. Come back to you :)

**Comment by ClimberExtensions** [comment]
Try version 1.1.1 I just uploaded

**Comment by SandegrenJohan** [comment]
Sorry to say but same About sign after import new version.
I come back, we maybe have some sync problems somewhere. If we still have the old extension on our nodes.

**Comment by SandegrenJohan** [comment]
Thanks for all Help :) I did a mistake when I downloaded the latest version. Clone and Download as a zip. Not good!! Use latest version in built map instead works perfect!!
Now it's looks perfect again 👍
