### ISSUE TITLE
Even I select dimensions and measures I can not see my report

### ISSUE THREAD

**Issue by AraCV** [ClimberAB/ClimberCustomReport#16]
Hello everybody.

Thanks for help us sharing this ext. 
The issue is, I have been working with Sense Desktop 3.1.4, almost everything is good, I visualize the dimensions, measures and the organization section but the resultant table.
If I export it, I can see all my selections in Excel, nevertheless I really need to review my report before exporting.

![report_qlik_sense_desktop](https://cloud.githubusercontent.com/assets/27368104/24972545/632684fe-1f81-11e7-8dba-435b5b726e38.png)

I will really apreciate your comments.
Greetings from Mexico.

**Comment by mickeg** [comment]
This looks like there is something wrong with Bootstrap. Make sure you download the latest version of the Custom Report and install it.
If that doesn't work, the old version might be cached. Try and remove your browsing history and cache.
