### ISSUE TITLE
"Hide fields and sortbar" is not currently cached in localstorage

### ISSUE THREAD

**Issue by enzocorrini** [ClimberAB/ClimberCustomReport#2]
Hello there,

thank you for this wonderful plugin, it really makes a difference on limited resolution monitors, with the added bonus to easy switch between dimensions.
I expected, as you stated on qlikbranch ("Hide fields and sortbar is now cached in localstorage"), that the options interface status (show or hide) will be remembered, but at the moment this is not happening, even when switching from one sheet to another on the same project. I tried to hardcode some sort of default status, but my poor skills failed me :P .
Thank you in advance for reading me and keep up the good work!

**Comment by kfsjostrand** [comment]
Thank you enzocorrini, and great that you are using GitHub for issue tracking.
Do you get any errors in the console?
I've attached a screengrab where I showcase the show/hide cache feature. It would be great if you could record and share what happens while you try the same.

[Sales Discovery- Custom Report _ Ark - Qlik Sense - Google Chrome 2016-09-15 11_36_50.zip](https://github.com/ClimberAB/ClimberCustomReport/files/474259/Sales.Discovery-.Custom.Report._.Ark.-.Qlik.Sense.-.Google.Chrome.2016-09-15.11_36_50.zip)

**Comment by enzocorrini** [comment]
Here i am, sorry for the waiting.
Just now i installed the latest version and now the plugin happily saves the visibility status of your interface. Problem solved for me, thank you!
