### ISSUE TITLE
Custom Report not working in IE

### ISSUE THREAD

**Issue by bmgQLIK** [ClimberAB/ClimberCustomReport#20]
We are having an issue get this extension to work in IE.   Is this a known issue?

**Comment by ClimberExtensions** [comment]
Hi,
the Custom Report should work in IE as long as you are on a modern version of IE (11 or higher should be fine). Please give us some more details on the type of issues you are having and the versions of Qlik Sense, Extension and IE. Also check if you are getting any error messages in the web browser console (F12 in IE).

/Michael
