### ISSUE TITLE
Issue with Qlik Sense Desktop 3.2 SR3

### ISSUE THREAD

**Issue by RDBiswas** [ClimberAB/ClimberCustomReport#21]
![image](https://cloud.githubusercontent.com/assets/28409547/25724056/4979f28e-30cf-11e7-8f86-cfdb5ded3a44.png)

The extension was working perfect before i upgraded to the 3.2 SR3 version for the Qlik Sense desktop. Since i upgraded, the report won't render. Is this something that other users are facing as well?

**Comment by kfsjostrand** [comment]
Thanks for the feedback. When upgrading you also need to install the latest version of the Custom Report. The latest version of custom report is tested with QS 3.2 SR3. 
Delete the extension in QMC before installing the latest version. If the problem still appears, clear your browser cache or set the developer tools to disable cache. 
Good luck

**Comment by RDBiswas** [comment]
Fresh re installation did the trick. Thank you.


On May 4, 2017, at 1:53 PM, kfsjostrand <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the feedback. When upgrading you also need to install the latest version of the Custom Report. The latest version of custom report is tested with QS 3.2 SR3.
Delete the extension in QMC before installing the latest version. If the problem still appears, clear your browser cache or set the developer tools to disable cache.
Good luck
