### ISSUE TITLE
Problems Exporting Data

### ISSUE THREAD

**Issue by matscarrgard** [ClimberAB/ClimberCustomReport#23]
Hi,

Great extension! I however have some problems with Export Data hanging (see screenshot below). Running Qlik Sense Desktop 3.2 SR3. I can see the data without problems, but once I select Export, the Export Data and the bubbles keep going forever, and no export is presented. Have tried both clearing the cache and re-installing the latest version multiple times, also created a new table in Master Items, but gives the same issue.

Am I missing something?

Regards,

Mats

![image](https://cloud.githubusercontent.com/assets/10493286/25945941/ef560488-3659-11e7-86d1-b5f929197a7a.png)

**Comment by mickeg** [comment]
Hi, can you check in the About section in the extension and verify that it is the latest version and nothing cached? Are there any error messages in the Javascript console in Developer Tools? (Ctrl + Shift + I in Chrome).

//Mikael

**Comment by kfsjostrand** [comment]
3.2 SR3 has a bug in the Capability API. Try the newly released 3.2 SR4. 
//Karl

**Comment by NOD507** [comment]
Hi, im having the same issue with sense 3.2 SR4 desktop and server. Im using chrome dev tools with caching disabled.

At the console im seeing this message when trying to export.

![image](https://cloud.githubusercontent.com/assets/1448331/26554270/e5bf5916-4454-11e7-8224-47657d1fdf69.png)

Did a simple extension to test and it looks like a bug introduced in 3.2 SR3 and still in SR4 with the exportData method in the table api. it works fine in 3.2 SR1.

**Comment by ClimberExtensions** [comment]
Fixed in latest release 1.1.9
There is a bug in the Table API in Qlik Sense 3.2 SR3 & SR4, won't be fixed until QS Release June2016
