### ISSUE TITLE
Issue with 2 custom reports on the same sheet

### ISSUE THREAD

**Issue by svalmori** [ClimberAB/ClimberCustomReport#24]
Hi,
I appreciate very much your extension. I'm running Qlik Sense Desktop 3.2 SR3 on a sheet with 2 custom reports. The first one is working fine but on the second one I can't move column or hide fields/sortbar. All the actions made by mouse right clicking over the second report are applied on the first. 

Best Regards,
Simone.

**Comment by mickeg** [comment]
Hi and thank you for reporting this issue.

I have checked and can verify that this is a bug. I'll register it and we will see if we can add a fix for this in a upcoming release.

//Mikael

**Comment by ClimberExtensions** [comment]
Fixed in latest release 1.1.9
