### ISSUE TITLE
Menu list report listing How to make it sort from Hi to Lo ?

### ISSUE THREAD

**Issue by paulyeo11** [ClimberAB/ClimberCustomReport#25]
Hi 

I hope that the report listing can be sort , see the below image.
![report menu sort report from hi to lo](https://cloud.githubusercontent.com/assets/13136214/25994309/ffd0e92c-373f-11e7-9ce4-0014d6845006.png)

**Comment by ClimberExtensions** [comment]
Fixed in 1.1.11

**Comment by paulyeo11** [comment]
Hi Michael
Thank you very much for your help, it work fine now.
		

		Paul Yeo
DIrector
TDS Technology (S) P/L
Whatsapp +65 9326 1804
	





On Thu, Jun 1, 2017 at 6:43 PM +0800, "ClimberExtensions" <notifications@github.com> wrote:












Fixed in 1.1.11
