### ISSUE TITLE
Export is not working in Qliksense 3.2.3

### ISSUE THREAD

**Issue by ravinder765** [ClimberAB/ClimberCustomReport#26]
Hello,
I have been using this extension and i liked it but it is not working in Qliksense 3.2.3 when we trying to use the export option. please suggest/inputs how to resolve the issue 

Thanks,
Ravinder

**Comment by kfsjostrand** [comment]
There are major bugs in QS 3.2 SR3 and SR4 in one of the APIs most extensions use, like the Climber Custom Report. 
Revert back to 3.2 SR2 or wait for the 2017 June update (4.0)
