### ISSUE TITLE
Custom Report Dimension it is possible able to make it can sort from A to Z ?

### ISSUE THREAD

**Issue by paulyeo11** [ClimberAB/ClimberCustomReport#29]
Hi Sir

Thank you very much for make the visulisation box able to sort.  it is possible to make dimension box also able to sort. ?

![customer report sort in dimension](https://cloud.githubusercontent.com/assets/13136214/26775704/978a99a4-4a08-11e7-915b-50b93c3fba0d.png)

Thank you very much for your contribution,

Paul Yeo

**Comment by kfsjostrand** [comment]
There is a option in the property panel for the sort order of master items
Regards
Karl

**Comment by paulyeo11** [comment]
Hi Karl
I just manually move the dimension and it work now . Thank you very much.
		

		Paul Yeo
DIrector
TDS Technology (S) P/L
Whatsapp +65 9326 1804
	_____________________________

**Comment by ClimberExtensions** [comment]
![image](https://cloud.githubusercontent.com/assets/20192393/26780921/3f5d22f4-49ec-11e7-8454-701b1418ed2a.png)

**Comment by ClimberExtensions** [comment]
![image](https://cloud.githubusercontent.com/assets/20192393/26780947/6000cd62-49ec-11e7-81f5-63ebcce3e188.png)
//Karl
