### ISSUE TITLE
How can I change the titles?

### ISSUE THREAD

**Issue by csilva91** [ClimberAB/ClimberCustomReport#3]
Hi!

This extension is really awesome, I love it. 

My "problem" is basically the english on the titles (I'm from Chile). So I'm trying to change the "Select master object", "Dimensions" and "Measures" titles. 

I hope that you can understand my "problem", my english is a little hard for me but I'm trying.

Greetings and awesome extension!

**Comment by kfsjostrand** [comment]
Hi and thanks for the feedback.
I change the titles to be localized to the users language settings in the latest commit. Check it out and see if you like it.

**Comment by csilva91** [comment]
Perfect! That's what I want to show, thank you!
