### ISSUE TITLE
'Unhiding' after 'Hide fields/sortbar'

### ISSUE THREAD

**Issue by Liamhanninen** [ClimberAB/ClimberCustomReport#33]
Awesome extensions our users will love this! Quick question - when I click on 'Hide fields/sortbar' can I 'unhide' them? Apologies if this is obvious but I can see my users getting confused when they can't make any more edits to the table.

**Comment by ClimberExtensions** [comment]
Yes, once hidden you find the option to unhide in using the right-click-menu.
