### ISSUE TITLE
Click Selections to Underlying App

### ISSUE THREAD

**Issue by Evank08** [ClimberAB/ClimberCustomReport#34]
Hi there,

![example](https://user-images.githubusercontent.com/30272772/28339093-d2b3d4e0-6bbf-11e7-8e81-cec98cae330b.png)
I'm seeing the field selections made within the extension are not added as click selections in the underlying app. This prevents me from being able to bookmark custom reports.

I was wondering if you are able to add this or give steps to get this functionality added? I imagine I would need to leverage the selections API. 

Also, could you post an un-minified version of the code?

Thanks,
Evan
Qlik Solution Architect

**Comment by mickeg** [comment]
Hi Evan, 

the extension will remember selections by report so by toggle the different visualizations you can have several reports with different dimension and measure selections.

It wouldn't make much sense applying the selections to the selection bar, a selection in the dimension "Year" just tells the extension it should include that dimension. The selection bar needs a field value of for example "2017".

We used to have un-minified code but for simplicity for us and for everyone downloading the extensions we have chosen to only include minified files. 

//Mikael

**Comment by jiankuang** [comment]
Hi, Mikael,

Will it be possible to save the Dimensions and Measures user choose? I know we have a default state "bookmark", but it will be great if we can save Dimensions and Measures on the fly. 

Thanks,
Jian

**Comment by mickeg** [comment]
Hi all and sorry for the late response, summer vacation tend to do that :)

I will discuss these requirements with my colleagues in the dev team and update you guys when we have our roadmap set. This will probably be in mid september. 

Thanks for all your feedback!

//Mikael

**Comment by MichaelClimber** [comment]
Hi,
We will stick with having master items as the base for Custom Report so that will not change. It is a proven model that is also well supported by Qlik. As mentioned in a few other issues/requests we are looking at bookmarks and have a working internal beta.

Kind regards

Michael
