### ISSUE TITLE
No "total-line" in Excel export

### ISSUE THREAD

**Issue by HUDA1981** [ClimberAB/ClimberCustomReport#35]
Hi,

Really great extension!

I have only one question, when I export the date into an Excel-sheet I miss the “total line”.
(see screenshot below marked in yellow)
Am I missing something?

QlikSense:
![p1](https://user-images.githubusercontent.com/30692363/28920512-7c5e1aca-7852-11e7-9fff-c577730e54f2.png)

Excel:
![p2](https://user-images.githubusercontent.com/30692363/28920522-846a4018-7852-11e7-80a8-6a7c5080d415.png)

Many thanks in advanced for Help.
Regards,
Daniel

**Comment by cdecluseau** [comment]
Hi Team !
Just want to know if you plan to take a look at this issue ?
We just notice it and it could be a great improove.

**Comment by MichaelClimber** [comment]
We are using the native export function of Qlik Sense so this is working as designed.

Kind regards

Michael
