### ISSUE TITLE
Is there a solution if i want to show two measures when selecting only 1?

### ISSUE THREAD

**Issue by amien90** [ClimberAB/ClimberCustomReport#36]
### Description

Not an issue, but an request : Is there a solution if i want to show two measures when selecting only 1?

for example:

when selecting 1 dimension (country) and 1 measure (sales). the end users is allowed to select for sales different measures : YTD, LYTD, last4weeks etc. 

So the end users selects : country, sales, YTD and LYTD (last two are both in a seperate listbox) and then the CR will show:

Country, Sales YTD, Sales LYTD

Thanks in advanced

**Comment by mickeg** [comment]
Hi! Thanks for your request, I have put it on our list of possible features. If we decide to implement it I will update this issue. 

Thanks!
//Mikael
