### ISSUE TITLE
Exporting using virtual proxy

### ISSUE THREAD

**Issue by MelissaPluke** [ClimberAB/ClimberCustomReport#37]
### Description

I am using Qlik Sense Server, the latest June version, and using a virtual proxy. The overall extension is working wonderfully and is great!  I see that there is a known issue regarding exporting.  I was wondering, #1 if anyone had any creative solutions to using this and giving end users the ability to export this without having to manually type in the virtual proxy in the URL, and #2 is there an estimated or expected fix for this to be able to work in the future?  Thank you for your help!

### Steps to Reproduce
N/A
##### Expected behavior

N/A

##### Actual behavior

N/A
### Environment
```
[ ] Desktop
[X ] Enterprise
```
### Versions

* Extension version: latest
* Browser: Chrome
* Qlik Sense: Latest (June 2017) Enterprise version
* Operating system: 
* [Other relevant versions]

**Comment by mickeg** [comment]
Hi! Unfortunately we don't have a environment to test this and I will close the issue.
Please let us know if you find a solution in the future.

/Mikael

**Comment by MelissaPluke** [comment]
I would love to set up a meeting with you to walk through it so we could trouble shoot the issue.  Would that be possible?

**Comment by mickeg** [comment]
Hi, sorry but at the moment there is no way for us to find time for this. It's a matter of our available time, if the extension is being used in any of our customers environments and how critical the bug is. 

Sorry for the inconvenience and please keep an eye on the release notes in future releases. 

//Mikael
