### ISSUE TITLE
Addon ClimberCustomer Report

### ISSUE THREAD

**Issue by Robbertsam-sin** [ClimberAB/ClimberCustomReport#39]
Hi Climber,

is an extension coming to enable a pivot table in the Climber Custom Report? This would enable us to easily compare figures. It would be so valuable.

Kind regards,

Robbert

**Comment by MichaelClimber** [comment]
Hi,
There is such an option for our customers with subscription agreements but not released as open source.

Kind regards

Michael

**Comment by Robbertsam-sin** [comment]
Hi Michael,

Do you have a preview of the option? And what would be the subscription fee?

Kind Regards,

Robbert Sam-Sin

________________________________
[cid:image002.jpg@01D1E0FC.F518AAF0]
Robbert Sam-Sin
Sales Information Officer, Sales Information
Weena 850, 3014 DA Rotterdam, The Netherlands
Email: r.sam-sin@robeco.nl<mailto:r.sam-sin@robeco.nl>
Tel: +31 10 224 3573<tel:+31%2010%20224%203573>
robeco.com<http://www.robeco.com/>
