### ISSUE TITLE
Default dimensions and measures by visualization 

### ISSUE THREAD

**Issue by MathieuVibert** [ClimberAB/ClimberCustomReport#4]
Hi there,

Thanks for the great job! Your extension is really helpful for us.

We do have some sort of issue on it.

We would like to be able to choose default dimensions and values for each visualization.
Is it possible?
Choices we make remain in the app next time we connect but when we publish it, the new user has to make his own choices. Being able to define basic setup (dimension and measure) for each visualization could be really great!

Thanks for your help and again for the excellent work!

Best regards
Mathieu

**Comment by ClimberExtensions** [comment]
Hi,
thanks for the feedback!

Both preset defaults as well as user specific "bookmarks" (not using the actual bookmarks in Qlik Sense though) are on the road map for Custom Report. 

Kind regards
/Michael
