### ISSUE TITLE
Context Menu Actions for Adding/Removing/Switching Table Does Not Work In Qlik Sense September 2017 release

### ISSUE THREAD

**Issue by jayro7** [ClimberAB/ClimberCustomReport#41]
### Description

The context menu options for Add fields/Remove  fields/ Switch table do not work in the latest version of the climbercustomereport for the Qlik Sense September 2017 release.  

### Steps to Reproduce

1. Select a visulization
2. Right click on the table to bring up the context menu and click add fields.
An error is thrown in the source debugger with a call stack of
require.js:19 TypeError: b.select is not a function
    at o.d.selectItem (/resources/assets/client/client.js??1502824274034:2)
    at fn (eval at compile (require.js:21), <anonymous>:4:471)
    at require.js:38
    at o.$eval (require.js:20)
    at o.$apply (require.js:20)
    at HTMLLIElement.<anonymous> (require.js:38)
    at HTMLLIElement.dispatch (require.js:12)
    at HTMLLIElement.q.handle (require.js:12)
    at Object.trigger (require.js:13)
    at HTMLSpanElement.<anonymous> (require.js:13)

##### Expected behavior

Another menu should appear asking to select dimension or measure.

##### Actual behavior
Nothing happens.  Type Error is thrown in Javascript for the client.js definition for "general.components/context-menu/context-menu".

### Environment
```
[ ] Desktop
[ X] Enterprise
```
### Versions

* Extension version: 1.2.0
* Browser: Chrome 61.0.3163.100 (64 bit)
* Qlik Sense: qlik Sense September 2017 qliksenseserver: 11.14.3
* Operating system: Windows 10
* [Other relevant versions]

### Screenshots
![image](https://user-images.githubusercontent.com/2965117/31827581-cc75a86c-b57d-11e7-8324-cce210779c84.png)

![image](https://user-images.githubusercontent.com/2965117/31827602-d5af4f0a-b57d-11e7-902e-c477887feb24.png)

**Comment by mickeg** [comment]
Hi,

thank you for reporting this. I can recreate it and we will look into fixing this asap.

//Mikael

**Comment by jayro7** [comment]
Thanks!!

**Comment by edwardhallgren** [comment]
Fixed in version 1.2.3
