### ISSUE TITLE
Cache issue in ClimberCustomeReport Extension

### ISSUE THREAD

**Issue by TonyAdrien** [ClimberAB/ClimberCustomReport#42]
We are experiencing an issue in both dev an prod with the cache for the Custom Report extension.  We changed the Sales Qlik application to include Stock data and made those additional stock metrics available in the Climber extension (Custom Report).  The issue we have is when you access the Custom Report page in Qlik QAP we are unable to see the added metrics (see Fig 1 below).  We are provided with the original dimensions and metrics from the previous application that was published.  Only after refreshing the screen (F5) are the new dimensions and metrics visible.  I would be grateful if you could investigate and advise please.  We are using the latest release of QlikSense.

@mickeg Can you comment on this issue please, thanks in advance.

**Comment by MichaelClimber** [comment]
Hi Tony,
we are working on a new major release that could potentially solve your problem so please stay tuned. That said, we have not seen this problem with our existing customers so it could also be something in your environment...
