### ISSUE TITLE
Can´t Export Data on version 3.2 SR5

### ISSUE THREAD

**Issue by dtribia** [ClimberAB/ClimberCustomReport#45]
### Description

Can´t Export Data in Climber Custom Report Extension

### Steps to Reproduce

1. [Step one]
Select Export data options

2. [Step two]
After this nothing happens, no information or message is showed and table disappear

##### Expected behavior

Export Message showed and data file created do download

##### Actual behavior

Nothing happens

### Environment
```
[ ] Desktop
[x] Enterprise
```
### Versions

* Extension version: Last version updated on Dec-22-2017
* Browser: Chrome - Version 63.0.3239.132 (oficial version) 64 bits
* Qlik Sense: 3.2 SR5
* Operating system: windows 10
* [Other relevant versions]

### Screenshots
![climber report export data - file 2](https://user-images.githubusercontent.com/32339254/34615325-a6f9c8ea-f21b-11e7-8d96-1b57fd591780.jpg)
![climber report export data - file 1](https://user-images.githubusercontent.com/32339254/34615326-a7230fc0-f21b-11e7-9e56-de16b88cb51b.jpg)

Please see issue #43  is the same problem that happens to me

Please verify the problem as soon as possible, the extension is very good, however without export function we cant use it.

Thanks and best reagards

Denilson Tribia
IT Specialist - LATAM
denilson.tribia@pspcorporate.com

**Comment by edwardhallgren** [comment]
Fix for this in version 1.2.3
