### ISSUE TITLE
Bookmarking support

### ISSUE THREAD

**Issue by JJH86** [ClimberAB/ClimberCustomReport#46]
### Description

End users need bookmarking functionality. Whenever the end user has made a selection for the layout (columns, rows, measures), they should be able to save this view for their personal use in the future.

The current filter selections for data are stored in the bookmark

**Comment by cdecluseau** [comment]
Hi Team !
Just want to know if you plan to take a look at this issue ?
We just notice it and it could be a great improove.
Thanks for your help

**Comment by MichaelClimber** [comment]
Hi, 
we do have a plan for bookmarking selections and have a working solution internally but it will be a while longer before release. We are also still deciding whether to put that functionality in the Open Source version of the extension or if we save it for our subscribing customers using the Custom Report Plus.

Kind regards

Michael
