### ISSUE TITLE
Bookmark support

### ISSUE THREAD

**Issue by rkmkumar19** [ClimberAB/ClimberCustomReport#47]
Trying to save the bookmark for the users with this custom report extension , but I'm not able to save those selections which I have selected in the custom report.

Need possible or work around for this issue.

Thanks,
K

**Comment by MichaelClimber** [comment]
Hi Kumar,
Bookmarks is currently not supported but we recognize the need for that type of functionality and it may be included in future releases.

Kind regards

Michael

**Comment by rkmkumar19** [comment]
Okay, are you going to put that release in open source or paid one ? and how long does it take, may be in a month or a while to release?

Thanks,
k

**Comment by MichaelClimber** [comment]
Not decided yet but estimate release in 1-2 months.
