### ISSUE TITLE
Custom report layout being cached in the browser

### ISSUE THREAD

**Issue by sbrusse** [ClimberAB/ClimberCustomReport#49]
### Description

After creating a custom report the selected dims and measures are cached by the browser. Is it possibnle to disable this behaviour?

### Steps to Reproduce

1. Create a custom report by selecting some dims and measures
2. Close the browser session and close the browser
3. Open a new browser instance and open the app with the custom report extension

##### Expected behavior

I expect to start off with an empty report after closing the browser session and re-opening the app.

##### Actual behavior

The custom report is pre-polulated with the dims and measures that were selected before closing the browser session.

### Environment

Enterprise

### Versions

* Extension version: 1.2.2
* Browser: Chrome
* Qlik Sense: November 2017
* Operating system: Windows Server 2016
* [Other relevant versions]

**Comment by MichaelClimber** [comment]
Hi,
right now this is the way it should work and there is no setting in the extension to change it. 
That said, we have reviewed the entire handling of caching data and preset values. With the next major version of Custom Report the behavior is likely to change and other options to handle default states for the master items will be added. 

Kind regards

Michael
