### ISSUE TITLE
Does not respect new/reordering fields 

### ISSUE THREAD

**Issue by Peter-Karimeddini** [ClimberAB/ClimberCustomReport#51]
### Description

When fields are added or reordered, users lose their chosen column set, as the columns shift based on the column reorder.

### Steps to Reproduce

1. Install Custom Report.
2. Add 1 table of dummy data.
3. Load data.
3. Add a master table with some dimensions.
4. Add a Custom Report object.
5. Choose a column that isn't the first or last column.
6. Add more columns to the dummy data table before between & after existing columns.
7. Reload data.
8. Rearrange the columns in the master table.

##### Expected behavior

The field I had selected should stay selected regardless of order of fields or other fields being added/dropped.

##### Actual behavior

Changing the order of fields in the underlying master table after loading more columns causes the chosen columns to shift to other columns at the old positions (i'm guessing the underlying code remembers chosen columns by modern hence why the chosen column shifts when reordering columns).

### Environment
```
[X] Desktop
[X] Enterprise
```
### Versions

* Extension version: 1.2 & 1.3
* Browser: Chrome
* Qlik Sense: Nov 2017
* Operating system: Win 7

**Comment by KFredberg** [comment]
This will be fixed in a upcoming version we are working on. Stay tuned.

**Comment by Peter-Karimeddini** [comment]
Great, thank you. Any rough ETA on the next version?

**Comment by MichaelClimber** [comment]
We are not committing to a date yet but it should not be too long.
