### ISSUE TITLE
Does not use calculated column label

### ISSUE THREAD

**Issue by Peter-Karimeddini** [ClimberAB/ClimberCustomReport#52]
### Description

Dynamic column labels are not used in the Dimension/Measure selectors.

### Steps to Reproduce

1. Install Custom Report.
2. Add 1 table of dummy data.
3. Load data.
4. Add a master table with 1 column having a calculated label.
5. Add a Custom Report object.

##### Expected behavior

The column name listed under Dimensions or Measures should use the calculated column label.

##### Actual behavior

The column name under Dimensions or Measures is the contents of the field/expression as if a label was not specified.

### Environment
```
[ ] Desktop
[X] Enterprise
```
### Versions

* Extension version: 1.2
* Browser: Chrome
* Qlik Sense: Nov 2017
* Operating system: Win 7

### Screenshots

Master Table Definition:
![image](https://user-images.githubusercontent.com/19224163/36863840-dd710e5c-1d58-11e8-9eb2-a4822f6e1cfb.png)

Custom Report Result:
![image](https://user-images.githubusercontent.com/19224163/36863984-4267eb32-1d59-11e8-984e-5cdb1d40f23f.png)

**Comment by KFredberg** [comment]
Hi, try using a master item with a calculated label instead. The calculated value will not show as the name, but at least the expression won’t. The master item name will be shown as the label in the list. 
We are working on a solution for this that will come in a future update to the Custom Report along with a bunch of new features and improvements.

**Comment by Peter-Karimeddini** [comment]
Thank you, that's a good temporary alternative.
