### ISSUE TITLE
Master tables should not be added by default

### ISSUE THREAD

**Issue by sandip59** [ClimberAB/ClimberCustomReport#53]
### Description
When we create a Straight table and added to master visualization, by default that item is being added to the list. But there always should be a developer choice that which Master table item should be added and which should not. So if we have that option it would be good for us.
[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]
But there always should be a developer choice that which Master table item should be added and which should not. So if we have that option it would be good for us.
##### Actual behavior

[What actually happened]
When we create a Straight table and added to master visualization, by default that item is being added to the list.
### Environment
Qliksense
[ ] Desktop - Yes
[ ] Enterprise
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

### Screenshots

**Comment by edwardhallgren** [comment]
Hi,

We are working on a new version with big improvements and one of the things is that you add your master items to your visualization.  In the meanwhile you can tag you master items and then only use that tag for the custom report (see picture) 
![image](https://user-images.githubusercontent.com/27728137/38089177-cf70bff2-335e-11e8-887c-a9d5be96f858.png)

Br
Edward
