### ISSUE TITLE
Merged columns

### ISSUE THREAD

**Issue by brofey** [ClimberAB/ClimberCustomReport#54]
### Description

Two columns are merged if the Measure item is not the last in the columns list.
This bug has showed himself after updating sense to April 2018.

### Steps to Reproduce

1. Select one Dimension.
2. Select one Measure.
3. Select one Dimension.

##### Expected behavior

Colmns should be separeted correctly.

##### Actual behavior

Colmns are not separeted correctly.
Filtering dimension items in one column cause filtering items from other column due to incorrect separation.

### Environment

Desktop

### Versions

* Extension version: v1.3.2
* Browser: Google Chrome 65.0.3325.181, also checked in Mozzila Firefox 52.7.0 and got same behaviour
* Qlik Sense:  Qlik Sense Server April 2018
* Operating system: Windows 10

### Screenshots
![climber report bug](https://user-images.githubusercontent.com/17027460/39111439-c6236390-46dd-11e8-942e-142ced3a048c.PNG)

**Comment by MichaelClimber** [comment]
Hi, 
thank you for reporting the issue. We are aware that the extension currently does not work properly with the April release. A completely new version 2.0 will be released shortly which will work with April as well as older versions. The new version also include some nice new features. If you happen to be at Qonnections in Orlando please drop by our Booth in the Exhibition area for a demo and to receive an early copy of the new version :-).

Kind regards

Michael

**Comment by edwardhallgren** [comment]
Hi, We have now a new version of the extension 2.0.2 where this problem is fixed.

Br Edward

**Comment by brofey** [comment]
Thanks!
