### ISSUE TITLE
Export data generates a zero-byte file

### ISSUE THREAD

**Issue by MeirMalka** [ClimberAB/ClimberCustomReport#55]
### Description

I have qlik sense desktop 12.5.3
When i use this extension and try to export data, i see the file was downloading, but i cannot open it, and the size of the file is 0 bytes.
I try in many computers, open as administrator and nothing helped me.
Do you have an explanation for this?
(sorry for my bad english)
Thanks in advance

### Environment
```
Qlik Sense Desktop

```
### Versions
* 12.5.3

**Comment by edwardhallgren** [comment]
Hi, Please try the latest version of the extension. Br Edward

**Comment by MeirMalka** [comment]
Hi, the new version is very nice, thanks!
This plugin is simply awesome!
I know what the bug is now!
The name of the Visualization object is "Not in English".
It's worth listing it somewhere that people can handle it in the future, or if you have a way to fix it.
In any case thank you very much for the answer.

**Comment by kfsjostrand** [comment]
Hi MeirMalka,
We can't recreate the error you are receving. Could you provide as with an instruction on how to recreate the bug? Or perhaps provide us with an app?
Best regards
Karl

**Comment by MeirMalka** [comment]
Hi @kfsjostrand 
i create qvf file to test the bug
[ClimberABTest.zip](https://github.com/ClimberAB/ClimberCustomReport/files/2001203/ClimberABTest.zip)
Hope this helps you

**Comment by MeirMalka** [comment]
hi
Sorry for the delay, I was not here
I am using google chrome 66 (x64)
I have now checked again and the problem still exists.

**Comment by kfsjostrand** [comment]
This is an issues with Qlik Sense February 2018 and is fixed in February 2018 SR2.
See the release notes here
https://da3hntz84uekx.cloudfront.net/QlikSense/12.5/2/QlikSense_February_2018_Patch2_ReleaseNotes.pdf
