### ISSUE TITLE
Search is not Working 

### ISSUE THREAD

**Issue by Ashfaq184** [ClimberAB/ClimberCustomReport#56]
Hi,

I try to search in dimension and measures of climber report.
Sometimes search is not working and Sometimes it works but when I select any dimension or measure selection does not take effect.
I have to go and select Dimensions and Measures individually.

using latest version of QlikSense April 208

**Comment by kfsjostrand** [comment]
The search functionality is designed as the native QS search functionality when adding fields/dimensions/measures. If you press enter to select the search text need to match the entire name of the item you like to select. 
We might improve this in a future release, but right now it’s working as designed.

**Comment by kfsjostrand** [comment]
I misunderstood your issue. We had other users experience the same error when searching and selecting. This is fixed in version 2.1.0
