### ISSUE TITLE
Extension resets selected dimensions and measures while choosing them

### ISSUE THREAD

**Issue by brofey** [ClimberAB/ClimberCustomReport#57]
### Description

Unstable behaviour of extension with many dimensions and measures.
While choosing dimensions and measures sometimes it causes reset of selected dimensions\meausures to be shown in table.

### Steps to Reproduce

1. Load big data table (estimated 1.3 million of rows) with 30 dimensions and 8 measures.
2. Start selecting all dimensions and measures.
3. While selecting them extension began glitchy and suddenly clears all dimensions and measures.

##### Expected behavior

Buld custom report with all dimensions and measures.

##### Actual behavior

Extension resets dimensions and don't allow to choouse all.

### Environment

Enterprise

### Versions

* Extension version: v2.0.2
* Browser: Google Chrome 65.0.3325.181
* Qlik Sense:  Qlik Sense Server April 2018
* Operating system: Windows 10

### Screenshots
![dissappears](https://user-images.githubusercontent.com/17027460/40168370-fce5e5be-59cb-11e8-89b0-243f34fdf67e.gif)

**Comment by brofey** [comment]
Well, it seems that this bug dissapeared in 2.1.0 version.

But 2.1.0 have new bug with repeatly switching collumns if the users tries to sort it via table collumns(

**Comment by Lojdquist** [comment]
Hi,

This should be solved in v2.1.2, try upgrading and reopen the issue if the problem remains. (the version numbers have been updated so the old 2.1.2 is 2.1.1).

**Comment by kfsjostrand** [comment]
Hi Brofey,
We now implemented a proper fix for this in our latest release 2.3.0. https://github.com/ClimberAB/ClimberCustomReport/releases/tag/v2.3.0
We also implemented a new feature in Climber Custom Report Plus, which improves the behaviour with large apps. It's called Defer layout update. And here is a screenshot of it in action. 

![image](https://user-images.githubusercontent.com/20219900/43571982-a2e71790-963e-11e8-9001-81170e972de0.png)

You can get more information about our extensions offerings here
www.climberextensions.com
