### ISSUE TITLE
Error 404 - The requested resource cannot be found

### ISSUE THREAD

**Issue by sfutter** [ClimberAB/ClimberCustomReport#58]
Can you explain why the 'Export data' option may lead to a 404 error: "The URL is unknown"? Is there a solution to avoid this error? I am trying to export data in the Climber Custom Report into excel. Thank you

**Comment by kfsjostrand** [comment]
Hi sfutter,
Could you provide us with your QS version and Custom Report version so we can try to recreate your issue. 
Attach an app would also help us fix the error.

**Comment by edwardhallgren** [comment]
Please reopen if you still have this problem in latest version. Br Edward
