### ISSUE TITLE
Fully expand icon 

### ISSUE THREAD

**Issue by Quercos** [ClimberAB/ClimberCustomReport#59]
Dear,
When a user pushes the 'fully expand icon', the measures/dimensions etc disappear. But how can he go back to the original state (with measures/dimensions) ? It seems that once they choose this feature, they can no longer return. Right-Click doesn't show any 'unhide' possibility ?

**Comment by edwardhallgren** [comment]
Hi, Can't you see this option when you are right clicking? 
![image](https://user-images.githubusercontent.com/27728137/42092169-3a6a9094-7ba8-11e8-8f3e-231a24302160.png)
