### ISSUE TITLE
Extension not working under Qlik Sense 3.1 and creating interface issues

### ISSUE THREAD

**Issue by simonmurzeau** [ClimberAB/ClimberCustomReport#6]
Hi,
I was very hopeful to use this extension in my app as it's great for user self service. It worked as a charm in Qlik Sense 3.0 but as soon as I upgraded to 3.1 the extension stopped working. It also seems to be creating some interface issues with Qlik Sense where whole menu lables disappear. 

Thanks,
Simon

**Comment by kfsjostrand** [comment]
This should be resolved in the latest commit. Open up a new issue if it persists.
