### ISSUE TITLE
Dimensions & Measures not carried over on Sheet Duplication

### ISSUE THREAD

**Issue by Peter-Karimeddini** [ClimberAB/ClimberCustomReport#61]
### Description

Please see Issue #60 for background detail, as this is a follow-up.
If a user makes a set of selections they want to preserve, they should be able to duplicate the sheet and set the default state easily. Presently, the duplicated sheet does not carry over their selections, requiring a user wishing to do this to make their selections a 2nd time.

### Steps to Reproduce

1. Install Custom Report.
2. Add any data.
3. Load data.
3. Add a master table with some dimensions.
4. Add a Custom Report object.
5. Choose dimensions & measures.
6. Duplicate the sheet.

##### Expected behavior

The dimensions & measures selected on the original sheet should persist.

##### Actual behavior

The dimensions & measures are reset.

### Environment
```
[X] Desktop
[X] Enterprise
```
### Versions

* Extension version: 2.0.3 & 2.1.0
* Browser: Chrome 67
* Qlik Sense: Nov 2017
* Operating system: Win 10

**Comment by MichaelClimber** [comment]
Just a quick follow-up question on that. You don't want it to keep selecting the same selections once the copy is done and this is only for he one time when the object is created? (I.e. you still want it to create a copy and not a mirror of the original object?)

**Comment by Peter-Karimeddini** [comment]
Correct, just clonng the dimension & measure selections at the time of duplication, not syncing 2 instances.

**Comment by kfsjostrand** [comment]
This works if you make the Custom Report a master item. Then both objects will share the same id and also share cached session state. Unlink after duplication if the user doesn't want to share the state between the objects.
