### ISSUE TITLE
Dimension/Measure selections reset if selected too rapidly

### ISSUE THREAD

**Issue by gmen85** [ClimberAB/ClimberCustomReport#64]
If I select Dimensions/Expressions quickly (even at the rate of one per second), the extension shortly acts if I have chosen nothing: it deselects my selected ones and never shows anything. Using QS Enterprise v. April 08

**Comment by Lojdquist** [comment]
Hi,

This should be solved in v2.1.2, try upgrading and reopen the issue if the problem remains. (the version numbers have been updated so the old 2.1.2 is 2.1.1).
