### ISSUE TITLE
"Sort by Alphabetical versus Table order" is not sticking 

### ISSUE THREAD

**Issue by edettrey** [ClimberAB/ClimberCustomReport#66]
Create a custom climber report based on some random table order
Switch the preference from "Table order" to "Alphabetical".
The custom report appears to do just that :)

HOWEVER, when you log back in.... its back to the random table order (sigh)

**Comment by Lojdquist** [comment]
Hi,

This is working correctly for me. Remember if you update a property in the property panel the application must be saved (top the the left) in order for that change to be applied.
