### ISSUE TITLE
Dimensions/Measures can't be easily selected or deselected

### ISSUE THREAD

**Issue by OlegTroyansky** [ClimberAB/ClimberCustomReport#67]
Hi!

First of all, thank you for sharing this extension, it's very useful! 

I'm having issues with the basic functionality of the object. I connected a Master Table, and I see all available Dimensions and Measures. Then the strange behavior begins:

- Selecting the first Dimension usually works as expected
- After that, adding a second Dimension works only sometimes
- Clearing the selected Dimensions is also hard - may work eventually after 3-4 attempts.
- Similarly, selecting the first Measure might work, but then selecting the second Measure or clearing selections doesn't work or works only after several attempts.

Appreciate any clues you might offer...

best,
Oleg Troyansky

**Comment by sgrubicib** [comment]
Hello,

I can confirm the behavior (QS June 2018; both Desktop and Enterprise editions). It seems that the bug wasn't present in version 2.1.1 (published here on July 11th) so we've reverted.

**Comment by OlegTroyansky** [comment]
Sorry if this is a lame question - where can I find version 2.1.1 ?

**Comment by sgrubicib** [comment]
There are no lame questions - only lame answers. ;)

Go to the project page (https://github.com/ClimberAB/ClimberCustomReport), click "57 commits"; under "Commits on Jul 11, 2018" find the one with version 2.1.1, click the "<>" button on the far right, and you'll be presented with the snapshot of the project page from that point in time. From there, just use "Clone or download" button to download ZIP, just like you would with the current version.

Or just use this link: https://github.com/ClimberAB/ClimberCustomReport/tree/b350fe462fa27d4b9df1c816f2fe5eae38acb9d1 
:)

You can always go back to the most recent version by clicking Tree:b350fe462.. and selecting the big blue "Master".

**Comment by kfsjostrand** [comment]
We are looking into your issue, and will release a fix shortly. 
In the meantime you can find all our previous release with a changelog here. 
https://github.com/ClimberAB/ClimberCustomReport/releases

**Comment by OlegTroyansky** [comment]
Thank you very much for all the answers!

**Comment by kfsjostrand** [comment]
This is now fixed in version v2.2.0
https://github.com/ClimberAB/ClimberCustomReport/releases/download/v2.2.0/cl-custom-report-v2.2.0.zip

**Comment by OlegTroyansky** [comment]
Thank you!!!
