### ISSUE TITLE
Broken download link to version 2.1.3

### ISSUE THREAD

**Issue by JakobLibak** [ClimberAB/ClimberCustomReport#68]
Download link to version 2.1.3 is broken:

https://github.com/ClimberAB/ClimberCustomReport/releases/download/v2.1.3/cl-custom-report-v2.1.3.zip

**Comment by kfsjostrand** [comment]
Thanks for reporting. We had some issues with the 2.1.3 release and it was removed. 
Those issues are now resolved in 2.2.0.
https://github.com/ClimberAB/ClimberCustomReport/releases/download/v2.2.0/cl-custom-report-v2.2.0.zip
