### ISSUE TITLE
Master table rapidly changing position in Firefox

### ISSUE THREAD

**Issue by sgrubicib** [ClimberAB/ClimberCustomReport#69]
Hello,

The extension is amazing, thank you for all the work you've done. :)

But there's a bug in Firefox (61.0.1, 64-bit, Windows 10). The main table (the master visualization) keeps jumping from being to the right of Dimensions and Measures lists to being directly below the lists. It happens several times per second for the first few seconds after making a selection, and then it stops, provided that you do not move your mouse pointer.

Versions affected (that I know of): 2.1.1, 2.2.1
Browsers that seem to work okay: Chrome 67.0, Opera 54.0, Edge 38

Kind regards

**Comment by kfsjostrand** [comment]
Thanks for posting an issue.
This should be fixed in the latest release.
https://github.com/ClimberAB/ClimberCustomReport/releases/tag/v2.3.0

**Comment by sgrubicib** [comment]
It appears to be working. :)

Thanks for the quick fix!
