### ISSUE TITLE
Extension is not working in Qlik Sense Server

### ISSUE THREAD

**Issue by sbhagana** [ClimberAB/ClimberCustomReport#7]
I have uploaded extension on my Qlik Sense Server via QMC but it is not working.I have created Table also as mentioned in Extension description part and it is also working in my Qlik Sense Desktop but same is not working in Server.
It is giving me blank boxed as in Measure and Dimension fields. 
![image](https://cloud.githubusercontent.com/assets/22980448/19597790/5e38bc78-97b4-11e6-8dde-84b0b472221b.png)

**Comment by kfsjostrand** [comment]
This should be resolved in the latest commit. Open up a new issue if it persists.
