### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by MelissaPluke** [ClimberAB/ClimberCustomReport#70]
When creating a master table with master dimensions/expressions which contain expressions you can Show Details and see the descriptions. However, when adding that table to the Climber Report, the details are not shown even when enabling "Show Details" in the Climber Report.

**Comment by kfsjostrand** [comment]
This will be added in the next release. Stay tuned.

**Comment by kfsjostrand** [comment]
Added in 2.4.0

**Comment by edwardhallgren** [comment]
Hi, this is added from version v2.4.0.

Br
Edward
