### ISSUE TITLE
Virtual Proxy problem

### ISSUE THREAD

**Issue by kghovanlou** [ClimberAB/ClimberCustomReport#72]
Hi, not sure if this is really an 'issue', but we are running this extension on a June 2018 release Enterprise server with a virtual proxy suffix (e.g. /prod/ or /dev/). 
What we are finding is that when trying to export to excel that we get a 404 error. The address used (tempcontent) needs us to manually add the /prod/ suffix in order to download the file. 
Is there something we can do to make this work without manually changing the URL each time?

**Comment by kfsjostrand** [comment]
This is already fix. Upgrade to the latest version of Climber Custom Report. https://github.com/ClimberAB/ClimberCustomReport/releases/latest

**Comment by kghovanlou** [comment]
great thank you
