### ISSUE TITLE
Specific need

### ISSUE THREAD

**Issue by BFadwa** [ClimberAB/ClimberCustomReport#73]
Hi,
First of all, i want to thank for the extension, it helped me a lot. i'm migration some Qlikview apps to Qlik Sense, and i had to migrate a Ad-hoc Database, and your extension was the only solution.
I have some questions thought.
1- is it possible to switch a field from rows to column ? it was possible in QlikView.
2- is there a way to group the values of a field without using a pivot table (it doesn't respond to my need)? for example group by year, like in the screen shot.
![image](https://user-images.githubusercontent.com/42937535/44988443-f543a980-af8a-11e8-8409-13aa8dcba145.png)

Thank you very much for your work and you help.

Keep up :+1: 

Best regards,

Fadwa BOUZIYANE

**Comment by edwardhallgren** [comment]
Hi, 
1 - Unfortunately, this is not possible for a table in qlik sense (we're building this from the native Sense Table)
2 - In your example, if you have one dimension (by year) and  then just one expression, sum (engineering workload) then the dimensions will be grouped in a table

Br
Edward

**Comment by BFadwa** [comment]
Hi,

Thank you for your reply.

I understand the limits of the extension . but about the second issue, if you look at the screen shot , i have the year 16/17 repeated 3 times, and 15/16 twice.
Even thought, i use only one measure and one dimension.


Thank's again for your help.

Best regards,

Fadwa BOUZIYANE

**Comment by BFadwa** [comment]
Hi Edward,

Sorry to bother you again, but something's strange with the extension.

My users and I , are getting non identical results with the same selections.

is it normal? what's the issue ? 
I can't publish the app in the prod server if the extension is not working maybe even unstable.

Can you please help me on that ?

Best regards !

Fadwa Bouziyane.

**Comment by edwardhallgren** [comment]
Hi, What version of the extensions are you using and what version of Sense? //Edward

**Comment by BFadwa** [comment]
Good evening Edward,

Thank you for your reply,

here's the information you asked for :+1: 
![image](https://user-images.githubusercontent.com/42937535/45439930-5cfca180-b6bb-11e8-8d47-c816b9e1760e.png)
![image](https://user-images.githubusercontent.com/42937535/45439980-77367f80-b6bb-11e8-8128-8aa7940b4d3f.png)

**Comment by edwardhallgren** [comment]
Try to upgrade the Extension to the latest version. //Edward
