### ISSUE TITLE
missing climber.jpg

### ISSUE THREAD

**Issue by zucoa** [ClimberAB/ClimberCustomReport#74]
Hello - I loaded 2.4.2 with our June 2018 release and it looks as though the extension can't find the climber.jpg image.

![image](https://user-images.githubusercontent.com/22177573/46014831-a0cdae80-c09e-11e8-8a36-5da8a4a0fd53.png)

**Comment by ClimberExtensions** [comment]
Thank for reporting! Fixed in version 2.4.3. Br Edward
