### ISSUE TITLE
Need solution about the Climber extension bug

### ISSUE THREAD

**Issue by ShalakaKshirsagar** [ClimberAB/ClimberCustomReport#77]
There is an issue publishing sheets with using the Climber Custom Report feature.
 
In order to use it correctly, one needs to first create the master visualization, then drag the Climber custom report to the sheet.
If you add a master visualization to the app while having a Climber Custom Report already on the sheet it will not update (but just say invalid visualization)
 
The problem with production environment is that the master visualization does not port automatically to prod when the app is published, so since the visualization is not there, it does not help to add it afterwards either, because of above.
 
It would be great if we could use master visualizations in production as well.

**Comment by kfsjostrand** [comment]
Could you please provide us with the versions of Qlik Sense and Climber Custom Report you are using. This information will help us.

**Comment by kfsjostrand** [comment]
With the major 2.0 upgrade, we changed the id of the extension so it could be installed alongside the old version. You probably only have the new cl-custom-report in your production environment, and have both the old cl-customreport and the new in your development environment.
