### ISSUE TITLE
Multiple Climber Custom Reports Not Rendering in Qlik Sense Mashup

### ISSUE THREAD

**Issue by amblemind** [ClimberAB/ClimberCustomReport#78]
Greetings!

### Versions
* Extension version: 2.5.0
* Qlik Sense: Desktop 12.44.1 (November 2018)
* Browser: Chrome v71.0.3578.98 

### Description
I am attempting to create a mashup that includes more than one Climber Custom Report. My requirements are to be able to dynamically show a Climber Custom Report dynamically. The user should be able to toggle between different Climber Reports (from 5+ apps) but only one must be shown at a time.

The 1st Climber visualization displays just fine. However, when I add a Climber Custom Report from another Qlik app, the additional ones do not display any data. The visualization container "styling" is shown, but no data. 

![Example](https://user-images.githubusercontent.com/45864164/51869774-31e7b700-2317-11e9-9e1b-18c0c803971d.png)

### Console errors
Only a warning: "[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
t.init @ qlik-module.d0e7b21bd0aa7e8c7f52.js:526"

### Steps to Reproduce
1. Navigate to http://localhost:4848/dev-hub/
2. Create a New Mashup using the Basic Mashup Template
3. Pull in 2 or more Climber Custom Reports from 2 or more Qlik Apps
4. Note that only the 1st one shows any data

##### Expected behavior
I expect to see all Climber Visualizations that I add to my mashup to display as they do in the Qlik Sense app. Again I do not need to display more than one at a time, but do need to display reports from different apps.

**Comment by MichaelClimber** [comment]
Hi!
Thank you for taking the time to report this issue. We are aware of the problem and have a solution to fix it but since no paying customers currently have the issue it is a lower priority. We will report back here as soon as it is fixed.

Find out more about our extensions and the subscriptions [here](http://www.climberextensions.com).

Kind regards

Michael

**Comment by amblemind** [comment]
Looks like I need to become a paying customer! 😄

**Comment by MichaelClimber** [comment]
Haha, yeah, that would help with the prioritization :-). Just drop me a message and I'll tell you more about the pricing and all the additional features in the paid version.

**Comment by kfsjostrand** [comment]
Fix in 2.6.0. Export to image only works on the CR in the latest loaded app. Limitation in qlik.currApp() function.
