### ISSUE TITLE
Export to Excel Issue

### ISSUE THREAD

**Issue by johnsacco** [ClimberAB/ClimberCustomReport#8]
Great Extension, One issue I am having is when trying to export to excel I am getting a new tab which returns "Not Found". When looking through the console the error is Failed to load resource: the server responded with a status of 404. We are using Qlik Sense 3.0.3 (server)

Thanks!

**Comment by kfsjostrand** [comment]
This is resolved in 3.1 SR2. If you are not updating the server right now, see the readme for workaround.
