### ISSUE TITLE
Custom report + text colouring changes to cell colouring when swithing from straight to pivot table

### ISSUE THREAD

**Issue by okakay** [ClimberAB/ClimberCustomReport#80]
### Versions
* Extension version: 2.6.0
* Qlik Sense: Feb 19
* Browser:  Chrome

*Extension version can be found under About in the property panel of the extension in Edit-mode or in the Qlik Sense Dev-hub.*  

### Description
I have a straight table and a field that have an expression if the value is under 0 the text becomes red. But when I convert the straight table to Pivot table, instead of colouring the text the cell becomes red.

### Console errors
[Check the console of the browser for errors]  

*Chrome: Ctrl + Shift + J*   
*Internet Explorer: F12, reload the page after, since IE doesn't keep history*  
*Firefox: Ctrl + Shift + K*

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]
![StraighTable](https://user-images.githubusercontent.com/23098507/56034673-4b01e080-5d28-11e9-80da-5bfd8fe94fe5.PNG)
![PivotTable](https://user-images.githubusercontent.com/23098507/56034674-4b9a7700-5d28-11e9-9f80-c1a34c199b2a.PNG)

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information. 
(This particular issue is identified as a bug and will be fixed with upcoming releases.)
